version: "3"
services:
  # import the backend API and db
  # in the future they can run on a separate host
  dbadmin:
    extends:
      file: backend/docker-compose.yml
      service: dbadmin
    profiles:
      - all
      - local

  postgres:
    extends:
      file: backend/docker-compose.yml
      service: postgres
    profiles:
      - all
      - local

  api-cache:
    extends:
      file: backend/docker-compose.yml
      service: api-cache
    profiles:
      - all
      - local

  search:
    extends:
      file: backend/docker-compose.yml
      service: search
    profiles:
      - all
      - local

  directus:
    extends:
      file: backend/docker-compose.yml
      service: directus
    profiles:
      - all
      - local

  # Run sveltekit
  webapp:
    container_name: webapp
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    environment:
      - NODE_ENV=${WEBAPP_NODE_ENV:-development}
    build:
      context: ./webapp
      dockerfile: Dockerfile.webapp
      args:
        - WEBAPP_PORT=${WEBAPP_PORT:-3000}
    ports:
      - "${WEBAPP_PORT:-3000}:${WEBAPP_PORT:-3000}"
    depends_on:
      - directus
    networks:
      - caddy_network
    profiles:
      - all

networks:
  caddy_network:
    name: caddy_baas
    external: true
