version: "3"
services:
  dbadmin:
    image: adminer
    container_name: dbadmin
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "${DOCKER_LOCAL_LISTEN_ADDR:-127.0.0.1}:${DBADMIN_PORT:-8080}:8080"
    depends_on:
      - postgres
    networks:
      - caddy_network
    env_file:
      - ${PWD}/.env

  postgres:
    image: postgis/postgis:${PG_VERSION:-15.3.3}
    container_name: datastore
    ports:
      - "${DOCKER_LOCAL_LISTEN_ADDR:-127.0.0.1}:${PG_DB_PORT:-5432}:${PG_DB_PORT:-5432}"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    networks:
      - caddy_network
    volumes:
      # only .sh, .sql, .sql.gz files will be loaded in initdb.d
      - ./datastore/init:/docker-entrypoint-initdb.d
      - ./datastore/backup:/var/lib/postgresql/backup
      # pg_data folder has to be completely empty (ie no .gitkeep) for the initdb.d scripts to run
      - ./datastore/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_DB: ${PG_DB_DATABASE}
    env_file:
      - ${PWD}/.env

  api-cache:
    image: redis:${REDIS_VERSION:-7}
    container_name: api-cache
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    networks:
      - caddy_network

  search:
    image: getmeili/meilisearch:${MEILI_VERSION:-v1.0.2}
    container_name: search
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    volumes:
      # By default indexes and documents are deleted every time the container stops.
      # Use dedicated volume to keep data between reboots:
      - ./meilisearch/meili_data:/meili_data
    ports:
      - "${DOCKER_LOCAL_LISTEN_ADDR:-127.0.0.1}:${MEILI_PORT:-7700}:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-production}
      - MEILI_LOG_LEVEL=${MEILI_LOG_LEVEL:-INFO}
      - MEILI_MAX_INDEXING_MEMORY=${MEILI_MAX_INDEXING_MEMORY:-500Mb}
    networks:
      - caddy_network

  directus:
    container_name: directus
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    #image: directus/directus:${DIRECTUS_VERSION:-latest}
    build:
      context: ./directus
      dockerfile: Dockerfile.directus
      args:
        - DIRECTUS_VERSION=${DIRECTUS_VERSION:-latest}
    ports:
      - "${DOCKER_LOCAL_LISTEN_ADDR:-127.0.0.1}:${DIRECTUS_PORT:-8055}:${DIRECTUS_PORT:-8055}"
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./directus/uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./directus/extensions:/directus/extensions
    networks:
      - caddy_network
    depends_on:
      - api-cache
      - postgres
      - search
    env_file:
      - ${PWD}/.env
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: ${PG_DB_PORT:-5432}
      DB_DATABASE: ${DIRECTUS_DB_DATABASE}
      DB_USER: ${DIRECTUS_DB_USER}
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD}

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      CACHE_REDIS: "redis://api-cache:${REDIS_PORT:-6379}"
      CACHE_STATUS_HEADER: "x-directus-cache-status"

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}

      # CORS
      # dev only
      #CORS_ENABLED: "true"
      #CORS_ORIGIN: "true"
      #CORS_CREDENTIALS: "true"

      # LOGGING
      LOG_LEVEL: "${DIRECTUS_LOG_LEVEL:-info}"
      LOG_STYLE: "${DIRECTUS_LOG_STYLE:-pretty}"

      # we do not use this API for public facing
      # (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: "https://directus.example.com"

networks:
  caddy_network:
    name: caddy_baas
    external: true
