FROM node:lts-slim AS builder
ARG MAX_OLD_SPACE_SIZE=1024
ENV NODE_OPTIONS=--max-old-space-size=${MAX_OLD_SPACE_SIZE}
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
RUN npm prune --production

FROM node:lts-slim as run
WORKDIR /app
RUN rm -rf ./*
COPY --from=builder /app/package.json ./
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
EXPOSE ${WEBAPP_PORT:-3000}
# See if increase libuv thread pool size makes performance better
# The default value 4
# http://docs.libuv.org/en/v1.x/threadpool.html
ENV UV_THREADPOOL_SIZE=32
CMD [ "node", "build" ]