name: Server Build & Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # This action use the github official cache mechanism internally
      - name: Install sops
        uses: mdgreenwald/mozilla-sops-action@v1.4.1
        with:
          version: 3.7.3
      - name: Install age
        run: |
          curl -Lo age.tar.gz https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz
          tar xf age.tar.gz 
          chmod 755 age/age*
          sudo mv age/age /usr/local/bin
          sudo mv age/age-keygen /usr/local/bin
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Install rsync
        run: |
          if [ -z "$(which rsync)" ]; then
            apt-get update -qq && apt-get install -y -qq rsync
          fi
      - name: Check versions
        run: |
          echo sops && sops --version
          echo age && age --version
          echo rsync && rsync --version
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          path: main
      - name: Decrypt env files
        run: |
          cd main && sops --decrypt --input-type dotenv --output-type dotenv .enc.env > .env
          cd webapp && sops --decrypt --input-type dotenv --output-type dotenv .enc.env > .env
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.DEPLOY_SSH_PORT}} -H ${{ secrets.DEPLOY_SSH_HOST }}  >> ~/.ssh/known_hosts
      - name: Copy using rsync
        run: rsync -avz -e "ssh -p ${{ secrets.DEPLOY_SSH_PORT }}" ./main/ ${{ secrets.DEPLOY_SSH_USERNAME }}@${{ secrets.DEPLOY_SSH_HOST }}:/home/${{ secrets.DEPLOY_SSH_USERNAME }}/main/
      - name: Run build with SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          script: |
            cd /home/${{ secrets.DEPLOY_SSH_USERNAME }}/main
            docker compose down && docker compose up -d --build
      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: "datastore,caddy,webapp"
          # Only show last 100 lines of each
          #tail: '100'
